### ISSUE TITLE
Dropping URL in MP causes desyncs?

### ISSUE THREAD

**Issue by UndeadZeratul** [HDest-Community/Universal-Reloader#15]
From Chipp on the Discord Server:
It happens a few seconds after placing reloader on the ground (assemble or disassemble mode).
1. It's always after the particles show up.
2. Second player can't even see the reloader on the ground.

**Comment by MegaShinySnivy** [comment]
I can confirm this is the case, playing with a friend and I on ashes, had the same issue.

**Comment by UndeadZeratul** [comment]
Just leaving a note here for later, but I'm wondering if the desyncs is caused by these calls to `random()` in the `chug` state?

https://github.com/HDest-Community/Universal-Reloader/blob/master/zscript/universalreloader/items/universalReloader.zsc#L596-L597

**Comment by MegaShinySnivy** [comment]
> Just leaving a note here for later, but I'm wondering if the desyncs is caused by these calls to `random()` in the `chug` state?
> 
> https://github.com/HDest-Community/Universal-Reloader/blob/master/zscript/universalreloader/items/universalReloader.zsc#L596-L597

I'd agree that seems to be the case.

**Comment by UndeadZeratul** [comment]
https://forum.zdoom.org/viewtopic.php?t=78104

https://github.com/HDest-Community/Universal-Reloader/blob/master/zscript/universalreloader/items/universalReloader.zsc#L200

Huge props to Phantombeta for doing the investigation on this, it seems that building the craftable recipes in the `DrawHUDStuff` method only causes that list to be built for the player holding the reloader, not everyone else.  This means the list needs to be updated elsewhere, maybe redesigning the flow to update the current recipe in the actor states instead?

**Comment by UndeadZeratul** [comment]
oh whoops, didn't mean to auto-close that; wanna run some tests to confirm before I release it.  I was able to boot up two instances of GZDoom locally and could drop the URL just fine with the commit, so feel free to give the latest commits a spin yourself and let me know if it works or not

**Comment by MegaShinySnivy** [comment]
No issues to report with the URL at least!

**Comment by UndeadZeratul** [comment]
Since there hasn't been any new reports of desyncs since the change, I'll consider this fixed.
