### ISSUE TITLE
Add Gunsmith Pouch

### ISSUE THREAD

**Issue by UndeadZeratul** [HDest-Community/Universal-Reloader#2]
It would certainly fit thematically to include a pouch to store all your precious crafting materials, at least.  Since the URL was removed from Cozi's Offworld Wares, it also makes sense to migrate it here for the time being.

https://github.com/Deadondev/Cozis-Offworld-Wares/blob/main/zscript/Items/LogiBag.zsc

**Comment by Cryomundus** [comment]
I'd recommend using the sprites from the gunsmith pouch: https://dastrukar.gitlab.io/hddons-list/#gunsmithpouch-mohl as it'll be easier to acquire permission for it, as its still a bit too early to consider offworld-wares's stuff abandoned, and I'd rather avoid upsetting folks if they come back and see their stuff nicked. Otherwise, yeah, sounds good!

**Comment by UndeadZeratul** [comment]
That's fair, I agree that I we shouldn't just yank other repository's stuff without permission, however I did notice a bit of an absence with Offworld Wares which makes it a bit stickier of a situation.

I can reach out to Skelegant as they did the artwork for the original, and honestly I kind of like the fannypack look to it.

**Comment by UndeadZeratul** [comment]
Taking a look at the Gunsmith Pouch, I do agree that the two of those pouches (the purse for the merchant, too) would do better as I forgot the Logistics Bag held much more stuff than simply crafting ingredients.

We can reach out to Mohl/Skelegant to see if they're both cool with using their code/assets.

**Comment by UndeadZeratul** [comment]
I was able to get permission from Mohl to use the Gunsmith Pouch code, now we just need permission from Skelegant to use their art assets.

**Comment by UndeadZeratul** [comment]
Skelegant also gave their permission to use their sprites, so I'll look into adding the Gunsmith Pouch at some point
